### ISSUE TITLE
create checklist for PR reviewer (& block deployment if some checks not done?)

### ISSUE THREAD

**Issue by trz42** [EESSI/eessi-bot-software-layer#152]
We could add a checklist to a PR (either at the top comment or PR description) or at the end (i.e., if all builds succeeded). The checklist could comprise of the following items:

- [ ] did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [ ] is the PR up-to-date with the target branch in the repository (if not what are the differences)
- [ ] is/are the easyconfig/s being built included with the EB version used (if not why not)
- [ ] were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

If not all checks are done, deployment could be blocked.

**Comment by boegel** [comment]
Ideally we have automated checks for this - relying on humans to check these things is brittle, and bound to lead to mistakes...

**Comment by trz42** [comment]
> Ideally we have automated checks for this - relying on humans to check these things is brittle, and bound to lead to mistakes...

True. Maybe having checklists added automatically (and filled in by humans) could be an intermediate step to full automation?
